# Generated by Django 3.0.6 on 2020-07-14 13:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('mp3', models.FileField(upload_to='track/')),
                ('status', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'FollowersOnly')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'FollowersOnly')], default=0)),
                ('logo', models.FileField(upload_to='')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 7, 14, 13, 3, 1, 478782, tzinfo=utc))),
                ('songs', models.ManyToManyField(to='playlist.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
