# Generated by Django 3.0.6 on 2020-07-15 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20200715_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 49, 16, 417974, tzinfo=utc)),
        ),
    ]
