# Generated by Django 3.0.6 on 2020-07-15 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20200715_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 17, 51, 26, 504491, tzinfo=utc)),
        ),
    ]
